import { Color } from './color.enum';

export namespace Decks {

    export const LEVEL_1 = [
        {level:1,point:0,white:0,blue:3,green:0,red:0,black:0,color:Color.WHITE},
        {level:1,point:0,white:0,blue:0,green:0,red:2,black:1,color:Color.WHITE},
        {level:1,point:0,white:0,blue:1,green:1,red:1,black:1,color:Color.WHITE},
        {level:1,point:0,white:0,blue:2,green:0,red:0,black:2,color:Color.WHITE},
        {level:1,point:1,white:0,blue:0,green:4,red:0,black:0,color:Color.WHITE},
        {level:1,point:0,white:0,blue:1,green:2,red:1,black:1,color:Color.WHITE},
        {level:1,point:0,white:0,blue:2,green:2,red:0,black:1,color:Color.WHITE},
        {level:1,point:0,white:3,blue:1,green:0,red:0,black:1,color:Color.WHITE},
        {level:1,point:0,white:1,blue:0,green:0,red:0,black:2,color:Color.BLUE},
        {level:1,point:0,white:0,blue:0,green:0,red:0,black:3,color:Color.BLUE},
        {level:1,point:0,white:1,blue:0,green:1,red:1,black:1,color:Color.BLUE},
        {level:1,point:0,white:0,blue:0,green:2,red:0,black:2,color:Color.BLUE},
        {level:1,point:1,white:0,blue:0,green:0,red:4,black:0,color:Color.BLUE},
        {level:1,point:0,white:1,blue:0,green:1,red:2,black:1,color:Color.BLUE},
        {level:1,point:0,white:1,blue:0,green:2,red:2,black:0,color:Color.BLUE},
        {level:1,point:0,white:0,blue:1,green:3,red:1,black:0,color:Color.BLUE},
        {level:1,point:0,white:2,blue:1,green:0,red:0,black:0,color:Color.GREEN},
        {level:1,point:0,white:0,blue:0,green:0,red:3,black:0,color:Color.GREEN},
        {level:1,point:0,white:1,blue:1,green:0,red:1,black:1,color:Color.GREEN},
        {level:1,point:0,white:0,blue:2,green:0,red:2,black:0,color:Color.GREEN},
        {level:1,point:1,white:0,blue:0,green:0,red:0,black:4,color:Color.GREEN},
        {level:1,point:0,white:1,blue:1,green:0,red:1,black:2,color:Color.GREEN},
        {level:1,point:0,white:0,blue:1,green:0,red:2,black:2,color:Color.GREEN},
        {level:1,point:0,white:1,blue:3,green:1,red:0,black:0,color:Color.GREEN},
        {level:1,point:0,white:0,blue:2,green:1,red:0,black:0,color:Color.RED},
        {level:1,point:0,white:3,blue:0,green:0,red:0,black:0,color:Color.RED},
        {level:1,point:0,white:1,blue:1,green:1,red:0,black:1,color:Color.RED},
        {level:1,point:0,white:2,blue:0,green:0,red:2,black:0,color:Color.RED},
        {level:1,point:1,white:4,blue:0,green:0,red:0,black:0,color:Color.RED},
        {level:1,point:0,white:2,blue:1,green:1,red:0,black:1,color:Color.RED},
        {level:1,point:0,white:2,blue:0,green:1,red:0,black:2,color:Color.RED},
        {level:1,point:0,white:1,blue:0,green:0,red:1,black:3,color:Color.RED},
        {level:1,point:0,white:0,blue:0,green:2,red:1,black:0,color:Color.BLACK},
        {level:1,point:0,white:0,blue:0,green:3,red:0,black:0,color:Color.BLACK},
        {level:1,point:0,white:1,blue:1,green:1,red:1,black:0,color:Color.BLACK},
        {level:1,point:0,white:2,blue:0,green:2,red:0,black:0,color:Color.BLACK},
        {level:1,point:1,white:0,blue:4,green:0,red:0,black:0,color:Color.BLACK},
        {level:1,point:0,white:1,blue:2,green:1,red:1,black:0,color:Color.BLACK},
        {level:1,point:0,white:2,blue:2,green:0,red:1,black:0,color:Color.BLACK},
        {level:1,point:0,white:0,blue:0,green:1,red:3,black:1,color:Color.BLACK}
    ];

    export const LEVEL_2 = [
        
        {level:2,point:2,white:0,blue:0,green:0,red:5,black:0,color:Color.WHITE},
        {level:2,point:3,white:6,blue:0,green:0,red:0,black:0,color:Color.WHITE},
        {level:2,point:1,white:0,blue:0,green:3,red:2,black:2,color:Color.WHITE},
        {level:2,point:2,white:0,blue:0,green:1,red:4,black:2,color:Color.WHITE},
        {level:2,point:1,white:2,blue:3,green:0,red:3,black:0,color:Color.WHITE},
        {level:2,point:2,white:0,blue:0,green:0,red:5,black:3,color:Color.WHITE},
        {level:2,point:2,white:0,blue:5,green:0,red:0,black:0,color:Color.BLUE},
        {level:2,point:3,white:0,blue:6,green:0,red:0,black:0,color:Color.BLUE},
        {level:2,point:1,white:0,blue:2,green:2,red:3,black:0,color:Color.BLUE},
        {level:2,point:2,white:2,blue:0,green:0,red:1,black:4,color:Color.BLUE},
        {level:2,point:1,white:0,blue:2,green:3,red:0,black:3,color:Color.BLUE},
        {level:2,point:2,white:5,blue:3,green:0,red:0,black:0,color:Color.BLUE},
        {level:2,point:2,white:0,blue:0,green:5,red:0,black:0,color:Color.GREEN},
        {level:2,point:3,white:0,blue:0,green:6,red:0,black:0,color:Color.GREEN},
        {level:2,point:1,white:2,blue:3,green:0,red:0,black:2,color:Color.GREEN},
        {level:2,point:1,white:3,blue:0,green:2,red:3,black:0,color:Color.GREEN},
        {level:2,point:2,white:4,blue:2,green:0,red:0,black:1,color:Color.GREEN},
        {level:2,point:2,white:0,blue:5,green:3,red:0,black:0,color:Color.GREEN},
        {level:2,point:2,white:0,blue:0,green:0,red:0,black:5,color:Color.RED},
        {level:2,point:3,white:0,blue:0,green:0,red:6,black:0,color:Color.RED},
        {level:2,point:1,white:2,blue:0,green:0,red:2,black:3,color:Color.RED},
        {level:2,point:2,white:1,blue:4,green:2,red:0,black:0,color:Color.RED},
        {level:2,point:1,white:0,blue:3,green:0,red:2,black:3,color:Color.RED},
        {level:2,point:2,white:3,blue:0,green:0,red:0,black:5,color:Color.RED},
        {level:2,point:2,white:5,blue:0,green:0,red:0,black:0,color:Color.BLACK},
        {level:2,point:3,white:0,blue:0,green:0,red:0,black:6,color:Color.BLACK},
        {level:2,point:1,white:3,blue:2,green:2,red:0,black:0,color:Color.BLACK},
        {level:2,point:2,white:0,blue:1,green:4,red:2,black:0,color:Color.BLACK},
        {level:2,point:1,white:3,blue:0,green:3,red:0,black:2,color:Color.BLACK},
        {level:2,point:2,white:0,blue:0,green:5,red:3,black:0,color:Color.BLACK}
    ];

    export const LEVEL_3 = [
        {level:3,point:4,white:0,blue:0,green:0,red:0,black:7,color:Color.WHITE},
        {level:3,point:5,white:3,blue:0,green:0,red:0,black:7,color:Color.WHITE},
        {level:3,point:4,white:3,blue:0,green:0,red:3,black:6,color:Color.WHITE},
        {level:3,point:3,white:0,blue:3,green:3,red:5,black:3,color:Color.WHITE},
        {level:3,point:4,white:7,blue:0,green:0,red:0,black:0,color:Color.BLUE},
        {level:3,point:5,white:7,blue:3,green:0,red:0,black:0,color:Color.BLUE},
        {level:3,point:4,white:6,blue:3,green:0,red:0,black:3,color:Color.BLUE},
        {level:3,point:3,white:3,blue:0,green:3,red:3,black:5,color:Color.BLUE},
        {level:3,point:4,white:0,blue:7,green:0,red:0,black:0,color:Color.GREEN},
        {level:3,point:5,white:0,blue:7,green:3,red:0,black:0,color:Color.GREEN},
        {level:3,point:4,white:3,blue:6,green:3,red:0,black:0,color:Color.GREEN},
        {level:3,point:3,white:5,blue:3,green:0,red:3,black:3,color:Color.GREEN},
        {level:3,point:4,white:0,blue:0,green:7,red:0,black:0,color:Color.RED},
        {level:3,point:5,white:0,blue:0,green:7,red:3,black:0,color:Color.RED},
        {level:3,point:4,white:0,blue:3,green:6,red:3,black:0,color:Color.RED},
        {level:3,point:3,white:3,blue:5,green:3,red:0,black:3,color:Color.RED},
        {level:3,point:4,white:0,blue:0,green:0,red:7,black:0,color:Color.BLACK},
        {level:3,point:5,white:0,blue:0,green:0,red:7,black:3,color:Color.BLACK},
        {level:3,point:4,white:0,blue:0,green:3,red:6,black:3,color:Color.BLACK},
        {level:3,point:3,white:3,blue:3,green:5,red:3,black:0,color:Color.BLACK}
    ];

    export const TILE = [
        {point:3,white:3,blue:3,green:0,red:0,black:3},
        {point:3,white:0,blue:3,green:3,red:3,black:0},
        {point:3,white:3,blue:0,green:0,red:3,black:3},
        {point:3,white:0,blue:0,green:4,red:4,black:0},
        {point:3,white:0,blue:4,green:4,red:0,black:0},
        {point:3,white:0,blue:0,green:0,red:4,black:4},
        {point:3,white:4,blue:0,green:0,red:0,black:4},
        {point:3,white:3,blue:3,green:3,red:0,black:0},
        {point:3,white:0,blue:0,green:3,red:3,black:3},
        {point:3,white:4,blue:4,green:0,red:0,black:0}
    ];
}
